[package]
name = "cctp_v1_with_executor"
version = "1.0.0"
authors = []

[addresses]
cctp_v1_with_executor = "_"
executor = "_"
executor_requests = "_"
token_messenger_minter = "_"

[dev-addresses]
message_transmitter = "0xebe6e5b8db973b4c8f5c3fbe7f5802e7a823b7ae4b70e5b6b1ce978418e5dad5"
token_messenger_minter = "0x4e0d4a160a8490565c7f61cd21531a320ccda0f55b9c7d20131b3717650db043"
aptos_extensions = "5ba1674a3ffa843ed88aa4a0a051b9a52f76459a8853e5cd62b22bcc488d2765"
stablecoin = "0xd59e6aa0af32155459919e5ed2792eecd8fedcac70f2bf59840431446ed36973"
deployer = "c06c5aa31d28c27be8345770a83b48314b829039ec5a33b79265216c13c66071"

[dependencies.executor]
git = "https://github.com/wormholelabs-xyz/example-messaging-executor.git"
rev = "aptos"
subdir = "aptos/executor"

[dependencies.executor_requests]
git = "https://github.com/wormholelabs-xyz/example-messaging-executor.git"
rev = "aptos"
subdir = "aptos/executor_requests"

[dependencies.TokenMessengerMinter]
local = "lib/aptos-cctp/packages/token_messenger_minter"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "aptos-release-v1.29"
subdir = "aptos-framework"

[dev-dependencies]
